roles:
  - name: geerlingguy.postgresql
    version: 4.0.0
  - name: AlexeySetevoi.clickhouse
    version: 1.12.1
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 10.1.0
  - name: community.postgresql
    version: 3.14.1