- name: Create directory for SSL cert and key
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'
  become: true
- name: Create conf file for SSL
  ansible.builtin.template:
    src: "../templates/ssl_pixbi.conf.j2"
    dest: "/etc/nginx/ssl/ssl_pixbi.conf"
    mode: '0644'
  become: true
- name: Generate cert and key
  ansible.builtin.command:
    argv:
      - openssl                   
      - req                       
      - -x509             
      - -nodes            
      - -days             
      - "365"
      - -newkey           
      - rsa:2048          
      - -keyout           
      - /etc/nginx/ssl/pixbi.key         
      - -out              
      - /etc/nginx/ssl/pixbi.crt         
      - -config           
      - /etc/nginx/ssl/ssl_pixbi.conf
  become: true
- name: Create nginx.conf file for PixBI
  ansible.builtin.template:
    src: "../templates/pixbi_nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  become: true
- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true
