- name: Install and configure Postgresql using geerlingguy.postgresql role
  block:
    - name: Install Postgresql
      include_role:
        name: geerlingguy.postgresql
      vars:
        postgresql_global_config_options:
          - option: unix_socket_directories
            value: '{{ postgresql_unix_socket_directories | join(",") }}'
          - option: log_directory
            value: 'log'
          - option: listen_addresses
            value: "*"
        postgresql_hba_entries:
          - {type: local, database: all, user: postgres, auth_method: peer}
          - {type: local, database: all, user: all, auth_method: peer}
          - {type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5}
        postgresql_databases:
          - name: "{{ pg_config_db_name }}"
            owner: "{{ postgres_username }}"
          - name: "{{ pg_bi_keys_db_name }}"
            owner: "{{ postgres_username }}"
        postgresql_users:
          - name: "{{ postgres_username }}"
            password: "{{ postgres_password }}"
            db: "{{ pg_config_db_name }}"
            port: 5432
          - name: "{{ postgres_username }}"
            password: "{{ postgres_password }}"
            db: "{{ pg_bi_keys_db_name }}"
            port: 5432
        postgresql_privs:
          - db: "{{ pg_config_db_name }}"
            roles: "{{ postgres_username }}"
            privs: ALL
            objs: ALL_IN_SCHEMA
            grant_option: true
          - db: "{{ pg_bi_keys_db_name }}"
            roles: "{{ postgres_username }}"
            privs: ALL
            objs: ALL_IN_SCHEMA
            grant_option: true
  when: not is_postgres_installed
  become: true